version: 2
jobs:
  build:
    working_directory: /go/src/github.com/isacikgoz/tldr
    docker:
      - image: isacikgoz/golang:1.12.5
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working dir
      - run:
          name: run tests
          command:
            go test --tags static ./... -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: push on codecov result
          command:
            bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
